// Code generated by gommon from xk/server/gommon.yml DO NOT EDIT.

package server

import dlog "github.com/dyweb/gommon/log"

func (srv *GrpcServer) SetLogger(logger *dlog.Logger) {
	srv.log = logger
}

func (srv *GrpcServer) GetLogger() *dlog.Logger {
	return srv.log
}

func (srv *GrpcServer) LoggerIdentity(justCallMe func() *dlog.Identity) *dlog.Identity {
	return justCallMe()
}

func (srv *HttpServer) SetLogger(logger *dlog.Logger) {
	srv.log = logger
}

func (srv *HttpServer) GetLogger() *dlog.Logger {
	return srv.log
}

func (srv *HttpServer) LoggerIdentity(justCallMe func() *dlog.Identity) *dlog.Identity {
	return justCallMe()
}

func (mgr *Manager) SetLogger(logger *dlog.Logger) {
	mgr.log = logger
}

func (mgr *Manager) GetLogger() *dlog.Logger {
	return mgr.log
}

func (mgr *Manager) LoggerIdentity(justCallMe func() *dlog.Identity) *dlog.Identity {
	return justCallMe()
}
