package util

import (
	"github.com/spf13/cobra"
	"github.com/xephonhq/xephon-k/pkg/storage/disk"
	"github.com/xephonhq/xephon-k/pkg/util"
	"os"
)

var (
	debug = false
)

var log = util.Logger.NewEntryWithPkg("k.cmd.util")

var RootCmd = &cobra.Command{
	Use:   "xkutil",
	Short: "Xephon K Util",
	Long:  "xkutil can be used for inspect and dump data file generated by Xephon K",
	Run: func(cmd *cobra.Command, args []string) {
		//log.Info(args)
		if len(args) < 1 {
			log.Info("must provide file to inspect")
			return
		}
		filePath := args[0]
		log.Info("inspect file %s", filePath)
		f, err := os.OpenFile(filePath, os.O_RDONLY, 0666)
		assert(err)
		// TODO: the magic check is wrong, it will try to read glide.yaml
		// TODO: print too much ....
		r, err := disk.NewLocalDataFileReader(f)
		assert(err)
		r.PrintAll()
		r.Close()
	},
}

func assert(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func Execute() {
	if RootCmd.Execute() != nil {
		os.Exit(-1)
	}
}

func init() {
	cobra.OnInitialize(initConfig)

	RootCmd.PersistentFlags().BoolVar(&debug, "debug", false, "debug")
}

func initConfig() {
	if debug {
		util.UseVerboseLog()
	}
}
