install:
  - go install ./cmd/xkb
  - go install ./cmd/xkc
  - go install ./cmd/xkd
  - go install ./cmd/xkutil
  - sh -c "cp $(which xkd) script/xephon-k-cassandra/node"
  # - go install ./playground/xnaive
  # - go install ./playground/xbucket
  # - go install ./playground/xapi
test:
  - go test -short -v -cover ./pkg/...
scripts:
  t:
    - go test -v -cover ./pkg/...
  runc:
    - docker run --name tsdb-cassandra -p 9042:9042 -d cassandra:3.9
  start:
    - docker start tsdb-cassandra
  f:
    - gofmt -d -l -w ./pkg
  d:
    - sh -c "xkd"
  naive:
    # FIXME: it seems to be my Fedora has some very strict network configuration for docker
    - sh -c "xnaive"
  bucket:
    - sh -c "xbucket"
  api:
    - sh -c "xapi"
  loc:
    - cloc --exclude-dir=vendor,.idea,playground --exclude-list-file=script/cloc_exclude.txt .
  loc-play:
    - cloc --exclude-dir=vendor,.idea --exclude-list-file=script/cloc_exclude.txt .
  release:
    - sh -c "zip xkb-linux-amd64.zip $(which xkb)"
    - sh -c "zip xkc-linux-amd64.zip $(which xkc)"
    - sh -c "zip xkd-linux-amd64.zip $(which xkd)"
    
